env:
  node: true
  jest: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - "*.test.js"
rules:
  no-underscore-dangle: 'off'
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 
    - error
    - ignorePackages
    - js: always